# Generated by Django 5.2.13 on 2026-06-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_compression', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressimage',
            old_name='compress_image',
            new_name='compressed_image',
        ),
    ]
