# Generated by Django 5.2.13 on 2026-06-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_compression', '0002_rename_compress_image_compressimage_compressed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressimage',
            old_name='compressed_image',
            new_name='compressed_img',
        ),
    ]
